name: gmaps_cloneish
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_polyline_points: ^2.1.0
  flutter_riverpod: ^2.6.1
  geolocator: ^13.0.2
  google_maps_directions: ^0.0.4
  google_maps_flutter: ^2.10.0
  permission_handler: ^11.3.1
  riverpod: ^2.6.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
